### ISSUE TITLE
getaddrinfo: Name or service not known

### ISSUE THREAD

**Issue by ProbablyRusty** [boardiq/consul-kv#2]
Any idea why I am seeing this?

```
/usr/share/ruby/2.0/net/http.rb:878:in `initialize': getaddrinfo: Name or service not known (SocketError)
    from /usr/share/ruby/2.0/net/http.rb:878:in `open'
    from /usr/share/ruby/2.0/net/http.rb:878:in `block in connect'
    from /usr/share/ruby/2.0/timeout.rb:52:in `timeout'
    from /usr/share/ruby/2.0/net/http.rb:877:in `connect'
    from /usr/share/ruby/2.0/net/http.rb:862:in `do_start'
    from /usr/share/ruby/2.0/net/http.rb:851:in `start'
    from /usr/share/ruby/2.0/net/http.rb:1367:in `request'
    from /usr/local/share/ruby/gems/2.0/gems/consul-kv-0.0.2/lib/consul/kv/connection.rb:33:in `standard_request'
    from /usr/local/share/ruby/gems/2.0/gems/consul-kv-0.0.2/lib/consul/kv/connection.rb:20:in `get'
    from /usr/local/share/ruby/gems/2.0/gems/consul-kv-0.0.2/lib/consul/kv/store.rb:20:in `block in get'
    from /usr/local/share/ruby/gems/2.0/gems/consul-kv-0.0.2/lib/consul/kv/store.rb:19:in `synchronize'
    from /usr/local/share/ruby/gems/2.0/gems/consul-kv-0.0.2/lib/consul/kv/store.rb:19:in `get'
    from ruby.rb:10:in `<main>'
```

```
require 'consul-kv'

Consul::KV.configure do |x|
  x.consul_host = 'http://127.0.0.1'
  x.consul_port = '8500'
  x.consul_prefix = 'v1/kv'
end

store = Consul::KV::Store.new
x = store['foo']
puts x
```

```
ruby 2.0.0p598 (2014-11-13 revision 48408) [x86_64-linux]
```

**Comment by jgwmaxwell** [comment]
Sorry for the slow reply - the issue here is setting the host with the 'http://' as part of it. A hostname doesn't have the protocol, and thus when trying to work out where it should be looking it doesn't understand.

Changing it to be:

``` ruby
Consul::KV.configure do |x|
  x.consul_host = '127.0.0.1'
  x.consul_port = '8500'
  x.consul_prefix = 'v1/kv'
end
```

like the example will fix that issue for you. Hope that helps!
